<?xml version="1.0" encoding="utf-8"?><Database Name="LinqDB" Class="SampleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ROHIT;Initial Catalog=LinqDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LinqDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Departments" Member="Departments">
    <Type Name="Department">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="ID" OtherKey="DeptID" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DeptID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Salary" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DeptID" OtherKey="ID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
</Database>